version: '3.8'

services:
  # Express.js API
  express-app:
    build: .
    container_name: portfolio-backend-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./public/assets:/app/public/assets
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - self-host-network

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - self-host-network

networks:
  self-host-network:
    driver: bridge