const ErrorCodes = {
  // Validation Errors (400 Bad Request) - VAL
  VALIDATION_MISSING_FIELD: "VAL-001",
  VALIDATION_INVALID_FORMAT: "VAL-002",
  VALIDATION_CONSTRAINT_FAILED: "VAL-003",
  VALIDATION_TYPE_MISMATCH: "VAL-004",
  VALIDATION_OUT_OF_RANGE: "VAL-005",
  VALIDATION_INVALID_OPTION: "VAL-006",
  VALIDATION_INCONSISTENT_DATA: "VAL-007",
  VALIDATION_DATE_INVALID: "VAL-010",

  // Database Errors - DBE
  DB_CONNECTION_FAILED: "DBE-001",
  DB_QUERY_FAILED: "DBE-002",
  DB_ENTITY_NOT_FOUND: "DBE-003",
  DB_DUPLICATE_ENTRY: "DBE-004",
  DB_CONSTRAINT_VIOLATION: "DBE-005",
  DB_TIMEOUT: "DBE-006",

  // Authentication & Authorization Errors - SEC
  AUTH_INVALID_CREDENTIALS: "SEC-001",
  AUTH_TOKEN_EXPIRED: "SEC-002",
  AUTH_TOKEN_INVALID: "SEC-003",
  AUTH_TOKEN_EXPIRED: "SEC-004",
  AUTH_TOKEN_MISSING: "SEC-005",
  AUTH_INSUFFICIENT_PERMISSIONS: "SEC-006",
  AUTH_RATE_LIMIT_EXCEEDED: "SEC-007",

  // File Handling Errors - FIL
  FILE_UPLOAD_FAILED: "FIL-001",
  FILE_DOWNLOAD_FAILED: "FIL-002",
  FILE_NOT_FOUND: "FIL-003",
  FILE_PERMISSION_DENIED: "FIL-004",
  FILE_SIZE_EXCEEDED: "FIL-005",
  FILE_FORMAT_INVALID: "FIL-006",

  // System & Application Errors - APP
  APP_UNHANDLED_EXCEPTION: "APP-001",
  APP_CONFIG_ERROR: "APP-002",
  APP_RESOURCE_LIMIT: "APP-003",
  APP_SERVICE_ERROR: "APP-004",
  APP_DEPENDENCY_MISSING: "APP-005",

  // CORS
  CORS_NOT_ALLOWED: "CORS-001",
};
module.exports = ErrorCodes;
